expname: default

device_ids: -1

data:
  type: lsun

  preload: true
  
model:
  framework: dcgan
  z_dim: 128
  loss_type: laplacian

  max_levels: 5
  k_size: 5
  sigma: 1
  n_channels: 3
  downscale: 2

training:
  epoch: 200
  batch_size: 128

  optimizer: adam
  lr_model: 1
  lr_z: 10

  lr_d: 0.001
  lamb: 0.2
  reproject: true
  
